services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    expose:
     - "6379"
    volumes:
      - redis_data:/data
    networks:
      - fakecheck_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  node_app:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    build:
      context: ./api/gateway/
    container_name: fakecheck_gateway
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ./api/nlp_predictor/model/model_metadata.json:/app/metadatas/model_metadata.json
    depends_on:
      redis: 
        condition: service_healthy
      python_service:
        condition: service_healthy
    networks:
      - fakecheck_net

  python_service:
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    build:
      context: ./api/nlp_predictor
    container_name: fakecheck_nlp_predictor
    ports:
      - "9000:9000"
    expose:
      - "9000"

    networks:
      - fakecheck_net

networks:
  fakecheck_net:
    driver: bridge
  
volumes:
  redis_data:
