services:
  node_app:
    build:
      context: ./api/gateway/
    container_name: fakecheck_gateway
    ports:
      - "3000:3000"
    volumes:
      - ./api/nlp_predictor/model/model_metadata.json:/app/metadatas/model_metadata.json
    depends_on:
      - python_service
    networks:
      - fakecheck_network

  python_service:
    build:
      context: ./api/nlp_predictor
    container_name: fakecheck_nlp_predictor
    ports:
      - "9000:9000" 
    networks:
      - fakecheck_network

networks:
  fakecheck_network:
    driver: bridge
